/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ca_halsafar_snesdroid_Emulator */

#ifndef _Included_ca_halsafar_snesdroid_Emulator
#define _Included_ca_halsafar_snesdroid_Emulator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ca_halsafar_snesdroid_Emulator
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ca_halsafar_snesdroid_Emulator_init
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     ca_halsafar_snesdroid_Emulator
 * Method:    initGraphics
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_ca_halsafar_snesdroid_Emulator_initGraphics
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     ca_halsafar_snesdroid_Emulator
 * Method:    resetConfig
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ca_halsafar_snesdroid_Emulator_resetConfig
  (JNIEnv *, jclass);

/*
 * Class:     ca_halsafar_snesdroid_Emulator
 * Method:    resetInputConfig
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ca_halsafar_snesdroid_Emulator_resetInputConfig
  (JNIEnv *, jclass);

/*
 * Class:     ca_halsafar_snesdroid_Emulator
 * Method:    processConfig
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ca_halsafar_snesdroid_Emulator_processConfig
  (JNIEnv *, jclass);

/*
 * Class:     ca_halsafar_snesdroid_Emulator
 * Method:    processGraphicsConfig
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ca_halsafar_snesdroid_Emulator_processGraphicsConfig
  (JNIEnv *, jclass);

/*
 * Class:     ca_halsafar_snesdroid_Emulator
 * Method:    getConfigFileName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ca_halsafar_snesdroid_Emulator_getConfigFileName
  (JNIEnv *, jclass);

/*
 * Class:     ca_halsafar_snesdroid_Emulator
 * Method:    onPause
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ca_halsafar_snesdroid_Emulator_onPause
  (JNIEnv *, jclass);

/*
 * Class:     ca_halsafar_snesdroid_Emulator
 * Method:    onResume
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ca_halsafar_snesdroid_Emulator_onResume
  (JNIEnv *, jclass);

/*
 * Class:     ca_halsafar_snesdroid_Emulator
 * Method:    loadRom
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ca_halsafar_snesdroid_Emulator_loadRom
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ca_halsafar_snesdroid_Emulator
 * Method:    isRomLoaded
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ca_halsafar_snesdroid_Emulator_isRomLoaded
  (JNIEnv *, jclass);

/*
 * Class:     ca_halsafar_snesdroid_Emulator
 * Method:    onTouchDown
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_ca_halsafar_snesdroid_Emulator_onTouchDown
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     ca_halsafar_snesdroid_Emulator
 * Method:    onTouchUp
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_ca_halsafar_snesdroid_Emulator_onTouchUp
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     ca_halsafar_snesdroid_Emulator
 * Method:    onTouchMove
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_ca_halsafar_snesdroid_Emulator_onTouchMove
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     ca_halsafar_snesdroid_Emulator
 * Method:    onKeyDown
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ca_halsafar_snesdroid_Emulator_onKeyDown
  (JNIEnv *, jclass, jint);

/*
 * Class:     ca_halsafar_snesdroid_Emulator
 * Method:    onKeyUp
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ca_halsafar_snesdroid_Emulator_onKeyUp
  (JNIEnv *, jclass, jint);

/*
 * Class:     ca_halsafar_snesdroid_Emulator
 * Method:    saveState
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ca_halsafar_snesdroid_Emulator_saveState
  (JNIEnv *, jclass, jint);

/*
 * Class:     ca_halsafar_snesdroid_Emulator
 * Method:    loadState
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ca_halsafar_snesdroid_Emulator_loadState
  (JNIEnv *, jclass, jint);

/*
 * Class:     ca_halsafar_snesdroid_Emulator
 * Method:    selectState
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ca_halsafar_snesdroid_Emulator_selectState
  (JNIEnv *, jclass, jint);

/*
 * Class:     ca_halsafar_snesdroid_Emulator
 * Method:    resetGame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ca_halsafar_snesdroid_Emulator_resetGame
  (JNIEnv *, jclass);

/*
 * Class:     ca_halsafar_snesdroid_Emulator
 * Method:    parse7Zip
 * Signature: (Ljava/lang/String;[Ljava/lang/String;[Lca/halsafar/filechooser/ZipFileType;)V
 */
JNIEXPORT void JNICALL Java_ca_halsafar_snesdroid_Emulator_parse7Zip
  (JNIEnv *, jclass, jstring, jobjectArray, jobjectArray);

/*
 * Class:     ca_halsafar_snesdroid_Emulator
 * Method:    unzip7ZFile
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ca_halsafar_snesdroid_Emulator_unzip7ZFile
  (JNIEnv *, jclass, jstring, jint, jstring, jstring);

/*
 * Class:     ca_halsafar_snesdroid_Emulator
 * Method:    unzipFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ca_halsafar_snesdroid_Emulator_unzipFile
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     ca_halsafar_snesdroid_Emulator
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ca_halsafar_snesdroid_Emulator_destroy
  (JNIEnv *, jclass);

/*
 * Class:     ca_halsafar_snesdroid_Emulator
 * Method:    step
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ca_halsafar_snesdroid_Emulator_step
  (JNIEnv *, jclass);

/*
 * Class:     ca_halsafar_snesdroid_Emulator
 * Method:    draw
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ca_halsafar_snesdroid_Emulator_draw
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
